// <auto-generated />
using System;
using DatabaseAPI_AQMS1._2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseAPIAQMS1._2.Migrations
{
    [DbContext(typeof(SensorDbContext))]
    [Migration("20230103033139_addedUsers")]
    partial class addedUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DatabaseAPI_AQMS1._2.Models.Sensor", b =>
                {
                    b.Property<string>("SensorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("StreamTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("co")
                        .HasColumnType("float");

                    b.Property<int>("mpd_Flr")
                        .HasColumnType("int");

                    b.Property<double>("no2")
                        .HasColumnType("float");

                    b.Property<double>("o3")
                        .HasColumnType("float");

                    b.Property<double>("pm25")
                        .HasColumnType("float");

                    b.Property<double>("so2")
                        .HasColumnType("float");

                    b.HasKey("SensorId");

                    b.ToTable("Sensors");
                });

            modelBuilder.Entity("DatabaseAPI_AQMS1._2.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
